# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# From gfplot .travis.yml:

warnings_are_errors: false

r_packages:
  - devtools
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

# From https://stackoverflow.com/questions/62937901/r-package-development-using-travis-ci-gets-error-due-to-failing-to-install-depen

global:
   - _R_CHECK_FORCE_SUGGESTS_: false